FROM nginx:alpine
COPY html/ /usr/share/nginx/html
COPY breizhicoop-nextcloud.gurvanhenry.com.conf /etc/nginx/conf.d/breizhicoop-nextcloud.gurvanhenry.com.conf
COPY breizhicoop-mattermost.gurvanhenry.com.conf /etc/nginx/conf.d/breizhicoop-mattermost.gurvanhenry.com.conf
COPY breizhicoop.gurvanhenry.com.conf /etc/nginx/conf.d/breizhicoop.gurvanhenry.com.conf
COPY breizhicoop-membres.gurvanhenry.com.conf /etc/nginx/conf.d/breizhicoop-membres.gurvanhenry.com.conf
